### ISSUE TITLE
Notification does not come if the system language is not English

### ISSUE THREAD

**Issue by Rak1ta** [Botspot/update-buddy#2]
My notification is working with active English. 
If Cyrillic (Russian) is selected, then there is nothing, I tried with `~/update-buddy/onstartup.sh`

RaspiOS 32bit Debian10

**Comment by Botspot** [comment]
This should now work as expected.
I took code from the Pi-Apps `add_english` function to make sure the English locale is in use during operation.

The core of this problem was that running `sudo apt update` would never say "`can be upgraded`", if another language was chosen.
